Repository AY2425S1-CS2103T-F13-1/tp, pull requests merged in 2024-11, with the labels that each got.

#212 Add command to mark attendance for Lessons
  src/main/java/seedu/address/logic/commands/lesson/MarkLessonAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/lesson/MarkLessonAttendanceCommandParser.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/test/java/seedu/address/logic/commands/lesson/MarkLessonAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/lesson/MarkLessonAttendanceCommandParserTest.java
Labels: type.Story, priority.High

#214 Change delete logic
  src/main/java/seedu/address/model/AddressBook.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Bug, severity.Medium, priority.Medium

#217 Change Edit Logic
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/consultation/Consultation.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/StudentLessonInfo.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/consultation/ConsultationTest.java
  src/test/java/seedu/address/model/lesson/LessonTest.java
  src/test/java/seedu/address/testutil/LessonBuilder.java
Labels: type.Bug, severity.Medium, alpha-bug

#215 Change message format if student has no courses
  src/main/java/seedu/address/logic/Messages.java
Labels: type.Bug, severity.Low, priority.Low

#227 Fix bug for invalid dates and times
  src/main/java/seedu/address/model/datetime/Date.java
  src/main/java/seedu/address/model/datetime/Time.java
  src/test/java/seedu/address/model/datetime/DateTest.java
Labels: type.Bug

#221 Update user and developer guides
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium

#229 DG: Add Use Cases
  docs/DeveloperGuide.md
Labels: priority.Medium

#231 Update guides: diagrams
  docs/DeveloperGuide.md
  docs/diagrams/ImportExport.puml
  docs/diagrams/Lessons/LessonsAndRelatedCommands.puml
  docs/diagrams/Lessons/MarkAttendanceCommandSequenceDiagram.puml
  docs/diagrams/Lessons/SequenceDiagramAddToLessonCommand.puml
Labels: priority.Medium

#236 Change user guide link
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.Low

#240 Fix Weird Bug that Causes Height of Consultation & Lesson Card to be inconsistent
  src/main/java/seedu/address/ui/ConsultationCard.java
  src/main/java/seedu/address/ui/LessonCard.java
Labels: type.Bug, priority.Medium, alpha-bug

#310 Address UI Glitch & Null Pointer Exception in Terminal
  src/main/java/seedu/address/ui/ConsultationCard.java
  src/main/java/seedu/address/ui/LessonCard.java
  src/main/java/seedu/address/ui/StudentCard.java
Labels: type.Bug

#312 Update find command in UG
  docs/UserGuide.md
  docs/images/findPeterJohnResult.png
Labels: type.Bug

#314 Update DG: Use Cases & UI Class Diagram
  docs/DeveloperGuide.md
  docs/diagrams/FullerLogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/FullerLogicClassDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.Bug

#319 Bugfix for add to lesson
  src/main/java/seedu/address/logic/commands/lesson/AddToLessonCommand.java
  src/test/java/seedu/address/logic/commands/lesson/AddToLessonCommandTest.java
Labels: type.Bug, severity.Medium

#320 Bugfix for add to consult command
  src/main/java/seedu/address/logic/commands/consultation/AddToConsultCommand.java
  src/test/java/seedu/address/logic/commands/consultation/AddToConsultCommandTest.java
Labels: type.Bug, priority.Medium

#321 PLEASE CHECK THIS Update error message example to show index
  src/main/java/seedu/address/logic/commands/consultation/AddToConsultCommand.java
Labels: severity.Low, priority.Low

#313 Add validation for filenames in Export
  docs/_sass/minima/_base.scss
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/consultation/ExportConsultCommand.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/consultation/ExportConsultCommandTest.java
Labels: type.Bug

#330 Update UG for Export and Import
  docs/UserGuide.md
Labels: priority.Low

#338 Update DG
  docs/DeveloperGuide.md
Labels: priority.Low
