Repository AY2425S1-CS2103T-F13-1/tp, pull requests merged in 2024-10, with the labels that each got.

#47 Add Feature: Find By (Student) Name
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/FindNameCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High

#56 Add Courses to GUI
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#58 Add Feature: Edit Student Information
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: priority.High

#69 Revert abstraction of FindCommand
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindNameCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High

#71 Add IsStudentOfCoursePredicate
  src/main/java/seedu/address/model/student/IsStudentOfCoursePredicate.java
  src/test/java/seedu/address/model/student/IsStudentOfCoursePredicateTest.java
Labels: priority.High

#72 Refactor person
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/student/Address.java
  src/main/java/seedu/address/model/student/Student.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/course/CourseTest.java
  src/test/java/seedu/address/model/student/AddressTest.java
  src/test/java/seedu/address/model/student/IsStudentOfCoursePredicateTest.java
  src/test/java/seedu/address/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/student/StudentTest.java
  src/test/java/seedu/address/model/student/UniqueStudentListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/StudentBuilder.java
  src/test/java/seedu/address/testutil/StudentUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.Medium

#76 Fix delete command format
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High

#78 Fix Student Name
  src/main/java/seedu/address/model/student/Name.java
  src/test/java/seedu/address/model/student/NameTest.java
Labels: priority.Medium

#83 Update FindCommandParser to handle multiple prefix arguments
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High

#85 Add semicolon as default prefix
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.Medium

#87 Allow Student Names to accept "," character
  src/main/java/seedu/address/model/student/Name.java
  src/test/java/seedu/address/model/student/NameTest.java
Labels: priority.Medium

#89 Add test cases
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.Medium

#92 Fix edit command syntax
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: priority.High

#94 Add export command
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
Labels: priority.High

#105 Fix Edit Feature Bugs Found
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: priority.Medium

#106 Add addconsult command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/consultation/AddConsultCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/consultation/AddConsultCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/consultation/AddConsultCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/consultation/AddConsultCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/ConsultationBuilder.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: priority.High

#115 Bugfix for find command
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.High

#111 Create Command Type and Integrate into All Commands
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/consultation/AddConsultCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/consultation/AddConsultCommandTest.java
Labels: priority.High

#120 Create GUI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/ConsultationCard.java
  src/main/java/seedu/address/ui/ConsultationListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StudentCard.java
  src/main/resources/view/ConsultationListCard.fxml
  src/main/resources/view/ConsultationListPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/TypicalConsultations.java
Labels: priority.High

#135 Fix export command to check extension and existing file
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
Labels: priority.Medium

#117 Test cases for find command
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/testutil/TypicalStudents.java
Labels: priority.Medium

#118 Add documentation for Consultation
  docs/DeveloperGuide.md
Labels: priority.Medium

#138 Update developer guide with export command
  docs/DeveloperGuide.md
Labels: priority.Medium

#146 Update Ui Display for Students in Consultations
  src/main/resources/view/DarkTheme.css
Labels: severity.VeryLow

#140 Add download to export command
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: priority.Medium

#149 Update Logic UML diagram
  README.md
  docs/DeveloperGuide.md
  docs/diagrams/FullerLogicClassDiagram.puml
  docs/images/FullerLogicClassDiagram.png
Labels: priority.Low

#152 Class diagram for Student class
  docs/DeveloperGuide.md
  docs/diagrams/Student.puml
Labels: priority.Low

#156 Update model uml in developer guide
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: priority.Low

#179 Add indices for add to consult
  src/main/java/seedu/address/logic/commands/consultation/AddToConsultCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/consultation/AddToConsultCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/consultation/AddToConsultCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/consultation/AddToConsultCommandParserTest.java
Labels: priority.Medium

#183 Create Temporary Lesson UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/lesson/exceptions/LessonNotFoundException.java
  src/main/java/seedu/address/ui/LessonCard.java
  src/main/java/seedu/address/ui/LessonListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/LessonListCard.fxml
  src/main/resources/view/LessonListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/lesson/exceptions/LessonNotFoundExceptionTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: priority.High

#167 Add import command
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ImportCommandParserTest.java
Labels: priority.Medium

#197 Add indices for add to lesson
  src/main/java/seedu/address/logic/commands/lesson/AddToLessonCommand.java
  src/main/java/seedu/address/logic/parser/lesson/AddToLessonCommandParser.java
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAndConsultationsAddressBook.json
  src/test/java/seedu/address/logic/commands/lesson/AddToLessonCommandTest.java
  src/test/java/seedu/address/logic/parser/lesson/AddToLessonCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalLessons.java
Labels: priority.Medium

#203 UI Display Past Consultations with a Red Background
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/consultation/AddConsultCommandParser.java
  src/main/java/seedu/address/logic/parser/lesson/AddLessonCommandParser.java
  src/main/java/seedu/address/model/consultation/Consultation.java
  src/main/java/seedu/address/model/datetime/Date.java
  src/main/java/seedu/address/model/datetime/Time.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/storage/JsonAdaptedConsultation.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/main/java/seedu/address/ui/ConsultationCard.java
  src/test/java/seedu/address/logic/commands/consultation/RemoveFromConsultCommandTest.java
  src/test/java/seedu/address/logic/commands/lesson/AddToLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/lesson/RemoveFromLessonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/consultation/AddConsultCommandParserTest.java
  src/test/java/seedu/address/logic/parser/lesson/AddLessonCommandParserTest.java
  src/test/java/seedu/address/model/consultation/ConsultationTest.java
  src/test/java/seedu/address/model/datetime/DateTest.java
  src/test/java/seedu/address/model/datetime/TimeTest.java
  src/test/java/seedu/address/model/lesson/LessonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedConsultationTest.java
  src/test/java/seedu/address/storage/JsonAdaptedLessonTest.java
  src/test/java/seedu/address/testutil/ConsultationBuilder.java
  src/test/java/seedu/address/testutil/LessonBuilder.java
Labels: priority.Low

#178 Add ExportConsult command
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/consultation/ExportConsultCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/consultation/ExportConsultCommandParser.java
  src/test/java/seedu/address/logic/commands/consultation/ExportConsultCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/consultation/ExportConsultCommandParserTest.java
Labels: priority.Medium

#204 Rework storage of student info in Lesson and add participation
  src/main/java/seedu/address/logic/parser/lesson/AddLessonCommandParser.java
  src/main/java/seedu/address/model/lesson/Lesson.java
  src/main/java/seedu/address/model/lesson/StudentLessonInfo.java
  src/main/java/seedu/address/storage/JsonAdaptedLesson.java
  src/main/java/seedu/address/storage/JsonAdaptedStudent.java
  src/main/java/seedu/address/storage/JsonAdaptedStudentLessonInfo.java
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/seedu/address/logic/commands/lesson/AddToLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/lesson/RemoveFromLessonCommandTest.java
  src/test/java/seedu/address/logic/parser/lesson/AddLessonCommandParserTest.java
  src/test/java/seedu/address/model/lesson/LessonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedLessonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedStudentLessonInfoTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/LessonBuilder.java
Labels: priority.High

#206 Improve Consultation List UI for Past Consultations
  src/main/java/seedu/address/ui/ConsultationCard.java
  src/main/java/seedu/address/ui/LessonCard.java
  src/main/resources/view/DarkTheme.css
Labels: priority.Low

#207 Link Students' Participation to Lessons UI
  src/main/java/seedu/address/ui/ConsultationCard.java
  src/main/java/seedu/address/ui/LessonCard.java
  src/main/resources/view/DarkTheme.css
Labels: priority.High

#209 Improve Lesson List UI for Past Lessons
  src/main/java/seedu/address/ui/LessonCard.java
  src/main/resources/view/DarkTheme.css
Labels: priority.Low

#210 Improve Layout of UI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium
